-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 25-01-2021 a las 13:51:05
-- Versión del servidor: 10.4.11-MariaDB
-- Versión de PHP: 7.4.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `literatura`
--
CREATE DATABASE IF NOT EXISTS `literatura` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci;
USE `literatura`;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `autores`
--

CREATE TABLE `autores` (
  `id_autor` int(10) NOT NULL,
  `nombre` varchar(255) COLLATE utf8mb4_spanish_ci NOT NULL,
  `biografia` text COLLATE utf8mb4_spanish_ci NOT NULL,
  `obras_reconocimiento` text COLLATE utf8mb4_spanish_ci NOT NULL,
  `imagen` varchar(255) COLLATE utf8mb4_spanish_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

--
-- Volcado de datos para la tabla `autores`
--

INSERT INTO `autores` (`id_autor`, `nombre`, `biografia`, `obras_reconocimiento`, `imagen`) VALUES
(0, 'ELÍSABET BENAVENT', 'Elísabet Benavent (Gandía,1984), conocida en sus redes sociales como Betacoqueta, es una escritora española de novelas de comedia romántica y autora de varios libros en los que destaca la saga En los zapatos de Valeria. \r\nEs licenciada en Comunicación Audiovisual por la Universidad Cardenal Herrera CEU de Valencia. Tras esa licenciatura se mudó a Madrid donde cursó el máster sobre Comunicación y Arte en la Universidad Complutense de Madrid, lugar donde actualmente reside la escritora. Trabajó durante casi siete años en el departamento de comunicación de una multinacional, hasta que en 2014 decidió dedicar todo su tiempo a la escritura. Actualmente, es muy reconocida por sus novelas romántico-contemporáneas, y con la colección de libros “Betacoqueta” publicada por Suma de letras.\r\n', 'Se alzó a la fama con la publicación de su primer libro En los zapatos de Valeria el 3 de enero de 2013 a través de una plataforma digital. Pocos meses después de la autopublicación en Internet, la Editorial Suma publicó la novela como primer libro de la saga \"Valeria\", que fue continuada por Valeria en el espejo (2013), Valeria en blanco y negro (2013), Valeria al desnudo (2013) y finalmente El diario de Lola (2015), donde narra la historia de Valeria y sus amigas en un viaje de la vida y el amor. La cifra de las ventas de la saga en la actualidad aumenta a más de 1.200.000 ejemplares. Gracias a este éxito, Netflix estrenó la primera temporada de Valeria, una serie basada en estas novelas. \r\nTras ello publicó otras sagas que tuvieron gran éxito como Silvia, Horizonte Martina, Mi isla y la bilogía Sofía.  \r\nEn 2018 estrenó Canciones y Recuerdos, que también se ha llevado al cine. Y sus últimas obras son Toda la verdad de mis mentiras y Un cuento perfecto.\r\nCon estas novelas Elísabet Benavent ya ha conseguido vender más de 2.000.000 de ejemplares.\r\n', 'images/authors/7.jpg'),
(28, 'ARTURO PÉREZ-REVERTE', 'Arturo Pérez-Reverte Gutiérrez (Cartagena, 1951) es un escritor, periodista y miembro de la Real Academia Española desde 2003. Se licenció en Periodismo y cursó a la vez estudios de Ciencias Políticas. Ejerció como reportero de guerra desde 1973 hasta 1994. Sus primeros pasos los dio en el diario Pueblo, donde permaneció 12 años. En 1977 fundó la revista Defensa. Desde 1978 trabajó en Televisión Española. A principios de los años 90 presentó en RNE La ley de la calle, un programa de radio. Entre 1993 y 1994 presentó el programa sobre la actualidad de la crónica negra Código Uno, también en Televisión Española, del que renegó posteriormente. \r\nEntonces, abandonó su labor como periodista para dedicarse por completo a la literatura. De su obra narrativa hay que destacar la tradición de la novela histórica y policiaca, también la trama de enredos desde una perspectiva romántica y los recursos folletinescos sobre un trasfondo histórico muy bien documentado. Muchas de sus obras han sido traducidas a varios idiomas y llevadas al cine. ', 'Arturo Pérez-Reverte ha publicado en total treinta novelas, dos libros de historia, un libro infantil, siete recopilaciones de sus artículos de prensa y textos breves, una recopilación con sus tuiteos sobre literatura y un libro de textos para acompañar a las fotografías de otro autor. Siete de las novelas forman parte de la saga Las aventuras del capitán Alatriste y otras tres de la serie Falcó.\r\nEntre sus obras publicadas, algunas de las que han obtenido más éxito son La tabla de Flandes, La piel del tambor, El club Dumas, Falcó, El capitán Alatriste, El asedio, Eva, y El oro del rey.\r\nA lo largo de su carrera ha recibido numerosos premios y galardones, de entre los que habría que destacar algunos tan importantes como el Goya, el Grand Prix de Literatura Policiaca de Francia, el Ondas, la Orden Nacional del Mérito, el Jean Monnet o el Palle Rosenkranz.\r\n', 'images/authors/8.jpg'),
(29, 'MEGAN MAXWELL', 'Megan Maxwell (Núremberg, 1965) seudónimo de María del Carmen Rodríguez del Álamo Lázaro, es una escritora española de novela romántica que también publica novela del subgénero romántico chick lit. \r\nHija de madre toledana y padre estadounidense, dejó Alemania a muy temprana edad para trasladarse con su madre a Madrid.  De hecho, uno de sus libros (Hola, ¿Te acuerdas de mí?) cuenta dos historias paralelas de amor, y una de ellas está basada en el noviazgo de sus padres, aunque modificando algunos datos y parte de la historia.\r\nTrabajó como secretaria en una asesoría jurídica durante varios años, hasta que su hijo enfermó y se dedicó a cuidarlo en casa. Al tener más tiempo comenzó a escribir novelas románticas bajo el seudónimo de \"Megan Maxwell\". Realizó un curso de literatura en línea y su profesora (editora) es la que publicó su primer libro.\r\n', 'Entre sus libros más leídos destaca la trilogía Pídeme lo que quieras o su serie Las guerreras Maxwell. Aunque también es muy conocida por su obra El día que el cielo se caiga.\r\nEn total, ha publicado más de treinta novelas, además de cuentos y relatos en antologías colectivas. Pídeme lo que quieras, su debut en el género erótico, fue premiada con las Tres Plumas a la mejor novela erótica que otorga el Premio Pasión por la Novela Romántica. Ademas, Warner Bros Spain y Versus Entertainment coproducirán la primera adaptación de esta saga.\r\nEntre sus reconocimientos destaca que en 2010 fue ganadora del Premio Internacional de Novela Romántica Villa de Seseña, en 2010, 2011, 2012 y 2013 recibió el Premio Dama de Clubromantica.com. En 2013 recibió también el AURA, galardón que otorga el Encuentro Yo Leo RA (Romántica Adulta) y en 2017 resultó ganadora del Premio Letras del Mediterráneo en el apartado de novela romántica.\r\n', 'images/authors/9.jpg'),
(30, 'CARLOS RUIZ ZAFÓN', 'Carlos Ruiz Zafón (Barcelona, 1964) fue un novelista español muy reconocido mundialmente. Estudió con los jesuitas en el colegio de San Ignacio de Sarrià, después se matriculó en Ciencias de la Información, y ya en el primer año le surgió una oferta para trabajar en el mundo de la publicidad. Llegó a ser director creativo en la delegación barcelonesa de la importante agencia McCann WorldGroup, hasta que en 1992 decidió abandonar la publicidad para consagrarse a la literatura. Fue uno de los autores más reconocidos de la literatura internacional de nuestros días y el escritor español más leído en todo el mundo después de Cervantes. Sus obras han sido traducidas a más de cincuenta idiomas. Por desgracia, falleció recientemente, el 19 de junio de 2020 debido a un cáncer de colon. ', 'En 1993 se da a conocer con El Príncipe de la Niebla, que forma con El Palacio de la Medianoche y Las Luces de Septiembre, la Trilogía de la Niebla. En 1998 llega Marina. En 2001 publica La Sombra del Viento, la primera novela de la saga de El Cementerio de los Libros Olvidados, que incluye El Juego del Ángel, El Prisionero del Cielo y El Laberinto de los Espíritus, un universo literario que se ha convertido en uno de los grandes fenómenos de las letras contemporáneas en los cinco continentes.\r\nAunque es cierto que su obra más importante es La sombra del viento, con 15 millones de ejemplares vendidos y ganador de numerosos galardones. La obra fue seleccionada en la lista confeccionada en 2007 por 81 escritores y críticos latinoamericanos y españoles entre los 100 mejores libros en lengua española de los últimos 25 años. \r\n', 'images/authors/10.jpg'),
(31, 'FERNANDO ARAMBURU', 'Fernando Aramburu Irigoyen (San Sebastián, 1959) es un escritor, poeta y ensayista español. Sus libros han sido traducidos a más de treinta idiomas, y destaca sobre todo por su obra más reconocida Patria, que ha vendido ya más de 200.000 copias solo en España. \r\nNació en una familia obrera que, en sus propias palabras, “chorreaba modestia por todas partes”. Es licenciado en Filología Hispánica por la Universidad de Zaragoza y trabajó en revistas impulsando la cultura. En 1985 se trasladó a Alemania donde fue profesor de español para hijos de inmigrantes en el estado de Renania del Norte-Westfalia, al oeste del país, pero abandonó la docencia en el año 2009 para dedicarse exclusivamente a la escritura. A comienzos de la década de 1980 fue creador y promotor del grupo de literatura Cloc en San Sebastián, experiencia que posteriormente se vio reflejada en su primera obra.\r\n', 'Como novelista, se dio a conocer con Fuegos con limón, en 1996. Su novela El trompetista del Utopía (2003) fue adaptada al cine por Félix Viscarret con el título Bajo las estrellas. Como poeta ha publicado varios poemarios bilingües, en español y euskera, tales como Ave Sombra (Itzal Hegazti, 1981) o Bruma y conciencia (Lambroa eta kontzientzia, 1993).  Su mayor reconocimiento vino con la antología de cuentos Los peces de la amargura (2006), en la que habló de las víctimas del terrorismo separatista vasco de la banda ETA. Este libro le valió el Premio Dulce Chacón de Narrativa Breve y el Premio Real Academia Española. En 2011 recibió el Premio Tusquets de Novela por Años lentos (2012).\r\nSus obras se han traducido a diferentes idiomas y han sido adaptadas al cine. En 2016 publicó Patria, un libro que generó un gran éxito en el público lector y recabó muy buenas críticas, otorgándole el Premio de la Crítica y el Francisco Umbral al Libro del Año.\r\n', 'images/authors/1.jpg'),
(32, 'JAVIER CASTILLO', 'Javier Castillo (Málaga, 1987) es un escritor español considerado como uno de los últimos fenómenos que dan sentido al término best seller con Todo lo que sucedió con Miranda Huff, que se aproxima a los terrenos del thriller psicológico. Javier creció en Málaga, estudió empresariales y más tarde hizo un máster en Management en ESCP Europe. Fue nominado a los Premios HOY Magazine 2020, unos premios que entrega la revista HOY Magazine y que ponen en valor y reconocimiento a la cultura nacional en el último año y dónde el autor fue nominado en la categoría a \'Mejor Escritor del Año\' por su novela La Chica de Nieve.', 'En 2014 publicó su primera novela, El día que se perdió la cordura, inicialmente en una plataforma electrónica. El éxito de ventas en Amazon llevó a varias editoriales a ofrecerle su edición, publicándose en papel en 2016 a través de la editorial Suma de Letras. Traducida a 10 idiomas y publicada en más de 63 países. Además, tras el gran triunfo que ha tenido el libro, Javier Catillo llegó a un acuerdo con las productoras Globomedia (The Mediapro Studio) y DeAPlaneta para adaptar la novela a una serie de televisión. \r\nSu segunda novela, El día que se perdió el amor, obtuvo también gran éxito de público y crítica, así como Todo lo que sucedió con Miranda Huff y La chica de nieve. Con ellas ha alcanzado el 1.000.000 de ejemplares vendidos. El juego del alma, de próxima publicación, será su quinta novela.\r\n', 'images/authors/2.jpg'),
(33, 'JUAN GÓMEZ-JURADO', 'Juan Gómez-Jurado (Madrid, 1977) es uno de los novelistas españoles más populares de su generación. Reina roja, una obra de misterio y suspense, ha sido uno de los títulos que se han mantenido entre los primeros puestos de lo más deseado por los lectores. Nació en Madrid en 1977, y se licenció en Ciencias de la Información en la Universidad San Pablo CEU. Ha trabajado como periodista en diferentes mediosː Radio España, Canal +, Cadena COPE, 40 Principales, ABC,3 La Voz de Galicia, El Mundo45 y ha colaborado con las revistas Qué Leer, Jot Down y New York Times Book Review. Entre septiembre de 2014 y junio de 2018 realizó junto a Raquel Martos la sección \"Personas físicas\" del programa de Onda Cero \"Julia en la onda\". Además, es uno de los componentes del podcast cultural Todopoderosos y Aquí Hay Dragones.', 'Comenzó a publicar novelas en el año 2006, como Espía de Dios que tuvo una gran acogida y fue seguida de Contrato con Dios (2007) y El emblema del traidor (2008), premiada en el VII Premio Internacional de Novela Ciudad de Torrevieja. Y entre sus éxitos podemos destacar que ha sido, con las novelas El emblema del traidor y Cicatriz, el autor más vendido en las plataformas digitales, según Amazon. Tras este gran triunfo, editoriales tradicionales se interesaron en su obra y, actualmente ya ha publicado con Ediciones B y con Planeta. Los libros de Juan Gómez-Jurado se suelen englobar dentro de la temática del thriller y la novela negra, hasta tal punto que se ha convertido en todo un exponente de este género.\r\nReina Roja, ha sido una de sus últimas obras más vendidas y con más éxito alcanzado, siendo el primer libro de la trilogía sobre el personaje Antonia Scott, seguido después de Loba Negra y Rey Blanco.\r\n', 'images/authors/3.jpg'),
(38, 'LAURA GALLEGO', 'Laura Gallego (Valencia, 1977) es una autora española de literatura infantil y juvenil, especializada en temática fantástica. Con once años decidió escribir un libro de fantasía con una amiga. Tardó tres años en terminarlo, aunque este nunca llegó a publicarse. Entonces ya tenía claro que quería ser escritora y durante años envió sus escritos a diversos concursos literarios. Durante este tiempo estudió Filología Hispánica, especializándose en Literatura.\r\nFundadora de la revista universitaria trimestral Náyade, ha sido codirectora de la misma desde 1997 hasta 2010. En la actualidad vive en Alboraya, donde continúa escribiendo.\r\n', 'Con 21 años recibió el Premio Barco de Vapor 1999 por Finis Mundi. Fue su primer galardón y el comienzo como escritora profesional. Después vendrían más novelas y cuentos, muchos de los cuales han sido publicados por Ediciones SM: como Las crónicas de la Torre, La leyenda del Rey Errante (Premio Barco de Vapor 2002), o la saga Memorias de Idhún. \r\nLaura Gallego ha explorado gran parte de los temas literarios: comienza escribiendo literatura histórico-fantástica, con su novela Finis Mundi; pero prueba también la ciencia ficción, con Las hijas de Tara; y más tarde la fantasía épica con Memorias de Idhún; sin olvidar tampoco su literatura infantil. \r\nActualmente su obra publicada comprende veintisiete novelas juveniles y algunos cuentos infantiles, con más de un millón de ejemplares vendidos solo en España y traducciones a dieciséis idiomas, entre los que se encuentran el inglés, el francés, el alemán y el japonés. Sus obras más populares entre los jóvenes lectores son Crónicas de la Torre, Dos velas para el diablo, Donde los árboles cantan, Alas de fuego, El Libro de los Portales y, especialmente, la trilogía Memorias de Idhún. En 2011 recibió el Premio Cervantes Chico por el conjunto de toda su obra, y en 2012 fue galardonada con el Premio Nacional de Literatura Infantil y Juvenil por su novela Donde los árboles cantan. Y la última trilogía publicada, Guardianes de la Ciudadela, ha sido también un gran éxito entre los más jóvenes.\r\n', 'images/authors/4.jpg'),
(39, 'SANTIAGO POSTEGUILLO', 'Santiago Posteguillo Gómez (Valencia, 1967) es un escritor español que ha alcanzado la fama por varias novelas cuya trama transcurre en la antigua Roma. El 16 de octubre de 2018 fue galardonado con el Premio Planeta por su novela más leída Yo, Julia.\r\nEstudió Literatura Creativa en la Universidad de Denison, en Granville (Ohio), y lingüística y traducción en Gran Bretaña. Fue director del Instituto Interuniversitario de Filología Valenciana. Aunque en la actualidad, trabaja como profesor titular en la Universitat Jaume I en Castellón,  donde imparte clases de lengua y literatura inglesa, con atención especial a la narrativa inglesa del siglo XIX, el teatro isabelino y la relación entre la literatura inglesa y norteamericana con el cine, la música y otras artes. ', 'En 2006 publicó su primera novela, Africanus: el hijo del cónsul, que inició su trilogía sobre Escipión el Africano. La segunda parte Las legiones malditas salió en 2008 y al año siguiente La traición de Roma. Rápidamente se convirtieron en superventas. \r\nEn 2011 inició una nueva trilogía con la publicación de Los asesinos del emperador, la primera novela de la serie sobre el emperador Trajano, que además quedó finalista en los Premios de la Crítica Literaria Valenciana. \r\nLe siguió Circo Máximo, su segunda novela de la trilogía sobre el emperador. En 2016 publicó La legión perdida, la tercera parte de su serie sobre Trajano y en 2017 El séptimo círculo del infierno, obra con la que concluía su trilogía sobre la historia de la literatura.\r\nY ya en 2018, el autor recibió el premio Planeta por su novela Yo, Julia, uno de los galardones de mayor prestigio e impacto en la literatura escrita en lengua española en todo el mundo. Por último, en 2020, el autor publica Y Julia retó a los dioses, el desenlace de su bilogía sobre Julia Domna, la emperatriz más poderosa del imperio romano.\r\n', 'images/authors/5.jpg'),
(40, 'SERGIO DEL MOLINO', 'Sergio del Molino Molina (Madrid, 1979) es un escritor y periodista español, autor de La España vacía, un ensayo que arrasó en venta y que a la vez abrió un debate social y político sobre la despoblación y sobre el efecto que el abandono del mundo rural ha tenido en el imaginario colectivo de los españoles. Periodista de formación y de oficio, fue reportero de prensa durante diez años y actualmente es colaborador asiduo de varios medios, tanto en diarios y revistas, como en radio y televisión. En 2005 obtuvo el Premio de Literatura Joven del Gobierno de Aragón, comunidad en la que reside. En 2013, la revista El Cultural, del diario El Mundo, lo seleccionó como uno de los doce narradores españoles menores de cuarenta años con más proyección.\r\nAdemás, colabora en diversos medios de comunicación, como El País, Cadena Ser, Onda Cero, Mercurio o Eñe.\r\n', 'La hora violeta (Literatura Random House, 2013), es la novela por la que recibió el Premio Ojo Crítico de Narrativa 2013, concedido por Radio Nacional de España, y el Premio Tigre Juan 2013, entre otros, y que además, ha sido traducida a varios idiomas. Desde su debut literario, en 2009, ha publicado la colección de relatos Malas influencias (2009), el ensayo literario Soldados en el jardín de la paz (2009), una antología de sus textos periodísticos más personales, El restaurante favorito de Nina Hagen (2011), y la que fue su primera novela No habrá más enemigo (2012), que fue elegida como uno de los diez libros más recomendados en mayo de 2012 por los libreros españoles de CEGAL en la web \"Los libreros recomiendan”. \r\nNo obstante, su obra más importante es La España vacía (2016) que se convirtió en un fenómeno editorial y abrió un debate social, cultural y político inédito en España. Además, recibió el Premio de los Libreros de Madrid al Mejor Ensayo y el Premio Cálamo al Libro del Año, y fue reconocido como uno de los diez mejores libros de 2016 en España por la inmensa mayoría de la prensa. Su última novela es La mirada de los peces (2017).\r\n', 'images/authors/6.jpg');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `generos`
--

CREATE TABLE `generos` (
  `id_genero` int(10) NOT NULL,
  `nombre_genero` varchar(255) COLLATE utf8mb4_spanish_ci NOT NULL,
  `descripcion_genero` text COLLATE utf8mb4_spanish_ci NOT NULL,
  `imagen` varchar(255) COLLATE utf8mb4_spanish_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

--
-- Volcado de datos para la tabla `generos`
--

INSERT INTO `generos` (`id_genero`, `nombre_genero`, `descripcion_genero`, `imagen`) VALUES
(1, 'romántico', 'Las novelas románticas son uno de los géneros más tratados a lo largo de la historia. <br>  Es cierto que se pueden desarrollar en todo tipo de espacios y mezclarse con otros géneros, pero el núcleo de su argumento siempre es la historia amorosa. Tiene un fuerte desarrollo a finales del siglo XVIII y principios del XIX, durante el periodo que conocemos como Romanticismo y en el que encontramos grandes representantes de este género como Jane Austen con obras como Orgullo y prejuicio, o las hermanas Emily y Charlotte Brontë con obras como Cumbres borrascosas y Jane Eyre respectivamente. En torno a este género también nacen otros subgéneros como la novela erótica, la novela rosa o la novela sentimental. Actualmente, la novela romántica contemporánea se basa en historias en las que la narrativa del amor ha cambiado, se ha diversificado y está lejos de ser lo que solía ser: ahora no todas las veces triunfa, pero siempre enseña. Concretamente en España, el género romántico parece haber optado en más de una ocasión por una perspectiva juvenil y erótica aunque también profunda y reflexiva. A continuación, podrás encontrar una lista con algunos de los libros que más destacan dentro de la novela romántica contemporánea española: ', 'images/novels/1.jpg'),
(2, 'realista', 'El siglo XIX es la gran época del realismo. Los grandes de este género se dan por todo el mundo: Benito Pérez Galdós, Emilia Pardo Bazán y Blasco Ibáñez en España; Dickens en Inglaterra; Zola y Balzac en Francia o Gógol en Rusia. Del género realista derivan subgéneros como la novela picaresca, la cual nació en España en el siglo XVI donde se mostraba la cruda realidad de la sociedad española; el realismo mágico, que añade al realismo un toque de fantasía y tiene en Gabriel García Márquez a su mayor exponente con obras como Cien años de soledad; la novela costumbrista; la novela social, que es similar a la costumbrista pero más centrada en problemáticas de los colectivos y no tanto de los individuos y la novela autobiográfica. El género humorístico es también un género e n s í m i s m o p e r o proviene en realidad d e l r e a l i s m o , concretamente de la n o v e l a p i c a r e s c a m e n c i o n a d a a n t e r i o r m e n t e . Subgéneros como las sátiras o l a s tragicomedias p e r t e n e c e n a e s e género. La serie de novelas más destacadas dentro del realismo contemporáneo español son las correspondientes a la tetralogía El cementerio de los libros olvidados, de Carlos Ruiz Zafón: ', 'images/novels/8.jpg'),
(3, 'histórico', 'Los libros dentro de este género solo pueden estar basados en hecho históricos y no en leyendas o mitos. A partir de ahí, pueden transitar hacia el misterio, el romanticismo, lo bélico o la aventura. También es un género que puede adentrarse en la biografía o autobiografía, donde el personaje principal narra unos hechos históricos en primera persona. Las novelas históricas son un tipo de novelas que deben seguir un estricto proceso de documentación histórica. Existen grandes novelas referentes de este género en la literatura contemporánea, como es el ejemplo de Sinuhé el egipcio (1945), de Mika Waltari. No cabe duda de que las novelas históricas con base en el antiguo Egipto son de las más aclamadas y, por ello, no podemos dejar de mencionar al egiptólogo y escritor Christian Jacq, quien ya ha conquistado a medio mundo con ellas. Otras obras mundialmente conocidas dentro de la novela histórica contemporánea universal son, por ejemplo, El médico (1986), de Noah Gordon, la saga Los pilares de la Tierra (1989-2017), de Ken Follet o la actual y popularizada saga Outlander, de la escritora estadounidense Diana Gabaldon. Las novelas de este género en España han tenido siempre una gran acogida. Autores españoles como Jose Luis Sampedro han forjado la base de la novela histórica contemporánea en nuestro país, con obras como La sonrisa etrusca (1985) o La vieja sirena (1990). Tras él, otros autores españoles se han decantado también por la novela histórica, pero de entre todos ellos cabe mencionar a Santiago Posteguillo, a quien hoy en día conocemos por su éxito en la novela histórica de la antigua Roma. Además, podemos destacar La Catedral del Mar (2006), de Ildefonso Falcones, considerada una de las obras más importantes y recientes de este género en nuestro país. La siguiente lista contiene una selección de títulos de las novelas históricas contemporáneas españolas más novedosas y con mayor acogida entre el público:', 'images/novels/13.jpg'),
(4, 'de terror o suspense', 'Posiblemente sea uno de los géneros que más se ha diversificado en los últimos años. El principal objetivo de este tipo de textos es crear inquietud en el lector, desde el propio suspense al horror absoluto. Se dice que el género de terror nace con Horace Walpole y su texto El Castillo de Otranto. Posteriormente podemos encontrar un amplio número de subgéneros como las novelas góticas de terror, asociadas generalmente al misterio alrededor del mundo delos muertos; las novelas de terror psicológico, de las cuales Edgar Allan Poe sería el representante por excelencia; las novelas de misterio; las novelas policíacas, donde la trama siempre gira en torno a la resolución de un caso criminal y en las cuales Arthur Conan Doyle y su Sherlock Holmes han tenido una gran influencia y, por último, las novelas negras, a q u e l l a s c e n t r a d a s exclusivamente en el “arte d e m a t a r ” y q u e s o n además el subgénero más nuevo y actual. En la literatura contemporánea de terror el primer nombre que nos viene a la mente es el de Stephen King. Sin duda, el escritor estadounidense, con más de sesenta novelas publicadas, ha sentado las bases de este género en la actualidad. Muchas de sus obras han sido incluso llevadas a la gran pantalla, como es el caso de Carrie, It o El resplandor. En el panorama de la literatura contemporánea española de suspense, las novelas negras o las de misterio son las más relevantes. De entre ellas, estas son algunas de las que más han sorprendido a los lectores: ', 'images/novels/20.jpg'),
(5, 'fantástico', 'Es la antítesis del Realismo, aunque a veces puede partir de una realidad para dar una versión de la misma en el futuro, como pueden ser el caso de La Odisea de Homero. Sin embargo, en la gran mayoría de las ocasiones, la ciencia ficción y el género fantástico crean mundos totalmente inexistentes y alternativos. Algunos de los ejemplos más clásicos que se encuadran en este género serían obras como Alicia en el País de las Maravillas (1865), de Lewis Carroll, la trilogía El Señor de los anillos (1937-1949), de J. R. R. Tolkien o la saga de Las crónicas de Narnia (1949-1952), de C. S. Lewis. Sin embargo, se dice que la primera novela precursora del género fantástico fue Entrebrumas (1926), de Hope Mirrlees. Hoy en día el género fantástico y de ciencia ficción es uno de los más populares en la literatura contemporánea actual. Se ha extendido notablemente a través de grandes sagas de fantasía como las novelas de Harry Potter, de J. K. Rowling o la saga Juego de Tronos, de George R. R. Martin. Actualmente destacan otras obras más novedosas como es el caso de la trilogía El nombre del viento, del escritor Patrick Rothfuss. Además, no podemos dejar de mencionar autores como Brandon Sanderson o, especialmente, Neil Gaiman, considerado uno de los mayores representantes de la literatura fantástica hoy en día, gracias a obras como Coraline, American Gods, Neverwhere o Stardust, todas ellas con adaptación en pantalla. En España, el género fantástico se ha desarrollado de manera más lenta que en otros países. Sin embargo, en la actualidad contamos con un gran número de autores españoles dedicados a este género que llevan años publicando sus obras de fantasía y ciencia ficción, como es el caso de Laura Gallego, la cual goza de reconocimiento a nivel mundial gracias a la saga Memorias de Idhún (2004-2006). Algunos de los títulos destacados más recientes dentro de la novela fantástica contemporáneas española son los siguientes: ', 'images/novels/27.jpg');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `novelas`
--

CREATE TABLE `novelas` (
  `id_novela` int(10) NOT NULL,
  `titulo` varchar(255) COLLATE utf8mb4_spanish_ci NOT NULL,
  `descripcion` text COLLATE utf8mb4_spanish_ci NOT NULL,
  `id_autor` int(10) NOT NULL,
  `id_genero` int(10) NOT NULL,
  `imagen` varchar(255) COLLATE utf8mb4_spanish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

--
-- Volcado de datos para la tabla `novelas`
--

INSERT INTO `novelas` (`id_novela`, `titulo`, `descripcion`, `id_autor`, `id_genero`, `imagen`) VALUES
(1, 'Toda la verdad de mis mentiras\r\n(2017) ', '¿Puede mantenerse una amistad a pesar de las mentiras? Una despedida de soltera en autocaravana. Un grupo de amigos… y muchos secretos. C o c o y M a r í n , a m b o s comparten piso en Madrid. Coco trabaja en una galería de arte, es una persona muy extrovertida, divertida y risueña, y está enamorada de Marín, en secreto. Marín t r a b a j a e n e l s e c t o r discográfico y es el chico ideal. Dentro de su grupo de amigos se encuentran Loren, Gus, que es el ex novio de Coco, Aroa, que es la ex novia de Marín y Blanca, que está a punto de casarse. Pero ojo, que no solo Coco es la que guarda secretos... Toda la verdad de mis mentiras de Elísabet Benavent. ¿Mentiras piadosas, mentiras egoístas? Confusión entre verdad y mentira, secretos que verán la luz. ¿Te gustaría conocerlos, verdad? ', 0, 1, 'images/novels/3.jpg'),
(2, 'El chico que dibujaba\r\nconstelaciones\r\n(2018) ', 'Una estrella por cada instante importante. Una marca que solo tú y yo sepamos descifrar. Serán las constelaciones de nuestra vida.\r\n\r\n\r\nEsta es una historia de amor, de sueños y de vida. La de Valentina. La chica que no sabía que tenía el mundo a sus pies, la que creció y empezó a pensar en imposibles. La que cazaba estrellas, la que anhelaba más, la que tropezó con él. Con Gabriel. El chico que dibujaba constelaciones, el valiente e idealista, el que confió en las palabras «para siempre», y creó los pilares que terminaron sosteniendo el pasado, el ahora, lo que fueron y los recuerdos que se convertirán en polvo.\r\n\r\n\r\nEl chico que dibujaba constelaciones es una novela romántica muy emotiva. Tiene unos protagonistas bien definidos y a los que es inevitable querer. Una prosa muy sentimental, muy cuidada y sencilla. Un ritmo rápido que avanza en una trama que cambia constantemente.\r\n', 0, 1, 'images/novels/4.jpg'),
(7, 'Olvídate de la lotería y\r\ndeja que te toque yo\r\n(2018)', 'Sara estudia Bellas Artes, pero cada vez le parecen menos bellas. Fran estudia Derecho, como quiere su familia, pero ni su corazón ni su vida giran en torno a ello. Bárbara actualiza sus redes sociales de manera constante y a ratitos estudia Diseño. \r\n\r\nLos tres amigos se conocieron hace años en una fiesta de disfraces y se creó entre ellos una bonita amistad en la que, sin saberlo, se fueron ocultando cosas. Pero la vida, los momentos y las sensaciones les hacen ver que algo falla.\r\n\r\n¿Será todo tan idílico como se quieren hacer creer? ¿Conseguirán sincerarse? Y, sobre todo, ¿qué pueden perder si se cuentan la verdad? Edad recomendada: novela romántica juvenil.\r\n\r\n\r\n¿Qué podemos perder? es una divertida comedia romántica juvenil que te enseña que, aunque la vida te lleve por muchos caminos, la dirección solo la decides tú.\r\n', 0, 1, 'images/novels/5.jpg'),
(8, '¿Qué podemos perder?\r\n(2020)', 'Sara estudia Bellas Artes, pero cada vez le parecen menos bellas. Fran estudia Derecho, como quiere su familia, pero ni su corazón ni su vida giran en torno a ello. Bárbara actualiza sus redes sociales de manera constante y a ratitos estudia Diseño. L o s t r e s a m i g o s s e conocieron hace años en una fiesta de disfraces y se creó entre ellos una bonita amistad en la que, sin s a b e r l o , s e f u e r o n ocultando cosas. Pero la vida, los momentos y las sensaciones les hacen ver que algo falla. ¿Será todo tan idílico como se quieren hacer creer? ¿Conseguirán sincerarse? Y, sobre todo, ¿qué pueden perder si se cuentan la verdad? Edad recomendada: novela romántica juvenil. ¿Qué podemos perder? es una divertida comedia romántica juvenil que te enseña que, aunque la vida te lleve por muchos caminos, la dirección solo la decides tú. ', 0, 1, 'images/novels/6.jpg'),
(9, '¿A qué estás esperando?\r\n(2020) \r\n', 'Can Drogo, piloto e hijo del d u e ñ o d e l a e m p r e s a aeronáutica High Drogo, es un hombre alto, guapo, adinerado, simpático… Puede elegir a la mujer que desee, y aunque disfruta de esa «magia especial» con la que le ha dotado la vida, en su interior siente que todas lo aburren. Por su parte, Sonia Becher es la mayor de cuatro hermanas y la propietaria de una empresa de eventos y de una agencia de modelos. Can ve en ella a una chica divertida, atrevida, sin tabúes, con la que se puede hablar de todo, incluido de sexo, pero poco más, pues considera que no es su tipo. Hasta que un día las sonrisas y las miradas de la joven no van dirigidas a él, y eso, sin saber por qué, comienza a molestarlo. ¿En serio Sonia va a sonreír a otros hombres estando él delante? Sexo. Familia. Diversión. Locura. Todo esto es lo que vas a encontrar en ¿A qué estás esperando?, una novela que te hará ver que, en ocasiones, tu corazón se desboca por quien menos esperas sin que puedas frenarlo. ', 0, 1, 'images/novels/7.jpg'),
(10, 'La sombra del viento\r\n(2001) ', 'La sombra del viento es la primera\r\nparte de la tetralogía conocida\r\ncomo El cementerio de los libros\r\nolvidados, de Carlos Ruiz Zafón, uno\r\nde los escritores de más prestigio\r\nque ha tenido nuestro país.\r\nU n a m a n e c e r d e 1 9 4 5 , u n\r\nmuchacho es conducido por\r\nsu padre a un misterioso lugar\r\noculto en el corazón de la ciudad\r\nvieja: el Cementerio de los Libros\r\nOlvidados. Allí, Daniel Sempere\r\nencuentra un libro maldito que\r\ncambia el rumbo de su vida y le\r\narrastra a un laberinto de intrigas\r\ny secretos enterrados en el alma oscura de la ciudad.\r\nUn misterio literario ambientado en la Barcelona de la primera mitad del siglo xx,\r\ndesde los últimos esplendores del Modernismo hasta las tinieblas de la posguerra.\r\nLa sombra del viento es sobre todo una trágica historia de amor cuyo eco\r\nse proyecta a través del tiempo. Con gran fuerza narrativa, el autor entrelaza\r\ntramas y enigmas a modo de muñecas rusas en un inolvidable relato sobre los\r\nsecretos del corazón y el embrujo de los libros cuya intriga se mantiene hasta\r\nla última página.\r\nLa sombra del viento fue un éxito literario en nuestro país con más de un millón de\r\nejemplares vendidos. ', 0, 2, 'images/novels/9.jpg'),
(11, 'El juego del ángel\r\n(2008) ', 'El juego del ángel es la segunda\r\nparte de la tetralogía conocida\r\ncomo El cementerio de los libros\r\nolvidados, de Carlos Ruiz Zafón,\r\nuno de los escritores de más\r\nprestigio que ha tenido nuestro\r\npaís.\r\nEn la turbulenta Barcelona de los\r\na ñ o s 2 0 u n j o v e n e s c r i t o r\r\nobsesionado con un amor\r\nimposible recibe la oferta de un\r\nmisterioso editor para escribir un\r\nlibro como no ha existido nunca,\r\na cambio de una fortuna y, tal\r\nvez, mucho más.\r\nCon estilo deslumbrante e impecable precisión narrativa, el autor de La sombra\r\ndel viento nos transporta de nuevo a la Barcelona del Cementerio de los Libros\r\nOlvidados para ofrecernos una gran aventura de intriga, romance y tragedia,\r\na través de un laberinto de secretos donde el embrujo de los libros, la pasión y la\r\namistad se conjugan en un relato magistral.\r\n“La próxima vez que quieras salvar un libro, no te juegues la vida... Te llevaré a un\r\nlugar secreto donde los libros nunca mueren.” ', 0, 2, 'images/novels/10.jpg'),
(12, 'El prisionero del cielo\r\n(2011) ', 'El prisionero del cielo es la tercera\r\nparte de la tetralogía conocida como\r\nEl cementerio de los libros olvidados,\r\nde Carlos Ruiz Zafón, uno de los\r\nescritores de más prestigio que ha\r\ntenido nuestro país.\r\nBarcelona, 1957. Daniel Sempere y su\r\namigo Fermín, los héroes de La sombra\r\ndel viento, regresan de nuevo a la\r\naventura para afrontar el mayor\r\ndesafío de sus vidas.\r\nJusto cuando todo empezaba a\r\nsonreírles, un inquietante personaje\r\nvisita la librería de Sempere y amenaza\r\ncon desvelar un terrible secreto que lleva enterrado dos décadas en la oscura\r\nmemoria de la ciudad. Al conocer la verdad, Daniel comprenderá que su destino\r\nle arrastra inexorablemente a enfrentarse con la mayor de las sombras: la que\r\nestá creciendo en su interior.\r\nRebosante de intriga y emoción, El prisionero del cielo es una novela magistral\r\ndonde los hilos de La sombra del viento y El juego del ángel convergen a través\r\ndel embrujo de la literatura y nos conduce hacia el enigma que se oculta en el\r\ncorazón del Cementerio de los Libros Olvidados. ', 0, 2, 'images/novels/11.jpg'),
(13, 'El laberinto de los espíritus\r\n(2016)', 'El laberinto de los espíritus es la cuarta\r\ny última parte de la tetralogía\r\nconocida como El cementerio de los\r\nlibros olvidados, de Carlos Ruiz Zafón,\r\nuno de los escritores de más prestigio\r\nque ha tenido nuestro país.\r\nEn la Barcelona de finales de los años\r\n50, Daniel Sempere ya no es aquel\r\nniño que descubrió un libro que habría\r\nde cambiarle la vida entre los\r\npasadizos del Cementerio de los Libros\r\nOlvidados. El misterio de la muerte de\r\nsu madre Isabella ha abierto un\r\nabismo en su alma del que su esposa\r\nBea y su fiel amigo Fermín intentan\r\nsalvarle.\r\nJusto cuando Daniel cree que está a un paso de resolver el enigma, una conjura\r\nmucho más profunda y oscura de lo que nunca podría haber imaginado\r\ndespliega su red desde las entrañas del Régimen. Es entonces cuando aparece\r\nAlicia Gris, un alma nacida de las sombras de la guerra, para conducirlos al\r\ncorazón de las tinieblas y desvelar la historia secreta de la familia… aunque a un\r\nterrible precio.\r\nEl laberinto de los espíritus es un relato electrizante de pasiones, intrigas y\r\naventuras. A través de sus páginas llegaremos al gran final de la saga iniciada\r\ncon La sombra del viento, que alcanza aquí toda su intensidad y calado, a la vez\r\nque dibuja un gran homenaje al mundo de los libros, al arte de narrar historias y al\r\nvínculo mágico entre la literatura y la vida. ', 0, 2, 'images/novels/12.jpg'),
(18, 'El asesinato de Sócrates\r\n(2016) ', 'Un filósofo que cambió el mundo. Un\r\ntenebroso vaticinio. Una intriga\r\nhistórica ambientada en el siglo más\r\napasionante de la Grecia clásica.\r\nGrecia, siglo v a. C.\r\nUn oscuro oráculo vaticina la muerte\r\nde Sócrates.\r\nUn recién nacido es condenado a\r\nmorir por su propio padre.\r\nUna guerra encarnizada entre Atenas\r\ny Esparta desangra Grecia.\r\nEl asesinato de Sócrates recrea magistralmente la época más extraordinaria de\r\nnuestra historia. Madres que luchan por sus hijos, amores imposibles y soldados\r\ntratando de sobrevivir se entrelazan de un modo fascinante con los gobernantes,\r\nartistas y pensadores que convirtieron Grecia en la cuna de nuestra civilización.\r\nA lo largo de las páginas de esta absorbente novela, brilla con luz propia la figura\r\ninigualable de Sócrates, el hombre cuya vida y muerte nos inspiran desde hace\r\nsiglos, el filósofo que marca un antes y un después en la historia de la humanidad. ', 0, 3, 'images/novels/14.jpg'),
(19, 'Las hijas del Capitán\r\n(2018)', 'Tres hermanas, dos mundos, una\r\nciudad.\r\nNueva York, 1936. La pequeña casa\r\nde comidas El Capitán arranca su\r\nandadura en la calle Catorce, uno\r\nde los enclaves de la colonia\r\nespañola que por entonces reside en\r\nla ciudad. La muerte accidental de\r\nsu dueño, el tarambana Emilio\r\nArenas, obliga a sus indomables hijas\r\nveinteañeras a tomar las riendas del\r\nnegocio mientras en los tribunales se\r\nr e s u e l v e e l c o b r o d e u n a\r\nprometedora indemnización.\r\nAbatidas y acosadas por la urgente necesidad de sobrevivir, las temperamentales\r\nVictoria, Mona y Luz Arenas se abrirán paso entre rascacielos, compatriotas,\r\nadversidades y amores, decididas a convertir un sueño en realidad.\r\nCon una lectura tan ágil y envolvente como conmovedora, Las hijas del Capitán\r\ndespliega la historia de tres jóvenes españolas que se vieron obligadas a cruzar un\r\nocéano, se asentaron en una urbe deslumbrante y lucharon con arrojo para\r\nencontrar su camino. Un tributo a las mujeres que resisten cuando los vientos\r\nsoplan en contra y un homenaje a todos aquellos valientes que vivieron —y viven\r\n— la aventura, a menudo épica y casi siempre incierta, de la emigración. ', 0, 3, 'images/novels/15.jpg'),
(20, 'Bilogía Julia Domna. Yo, Julia \r\n(2018-2020) ', 'Solo una mujer puede forjar una\r\ndinastía.\r\n192 d.C. Varios hombres luchan por un\r\nimperio, pero Julia, hija de reyes, madre\r\nde césares y esposa de emperador,\r\npiensa en algo más ambicioso: una\r\ndinastía.\r\nRoma está bajo el control de Cómodo,\r\nun emperador loco. El Senado se\r\nconjura para terminar con el tirano y los\r\ngobernadores militares más poderosos\r\npodrían dar un golpe de Estado: Albino\r\nen Britania, Severo en el Danubio o\r\nNigro en Siria. Cómodo retiene a sus\r\nesposas para evitar su rebelión y Julia, la\r\nmujer de Severo, se convierte así en\r\nrehén.\r\nDe pronto, Roma arde. Un incendio\r\nasola la ciudad. ¿Es un desastre o una oportunidad? Cinco hombres se disponen\r\na luchar a muerte por el poder. Creen que la partida está a punto de empezar.\r\nPero para Julia la partida ya ha empezado. Sabe que solo una mujer puede forjar\r\nuna dinastía. ', 0, 3, 'images/novels/16.jpg'),
(21, 'Y Julia retó a los dioses ', 'Cuando el enemigo es tu propio\r\nhijo… ¿existe la victoria?\r\nMantenerse en lo alto es mucho más\r\ndifícil que llegar. Julia está en la\r\ncúspide de su poder, pero la traición\r\ny la división familiar amenazan con\r\necharlo todo a perder. Para colmo\r\nde males, el médico Galeno\r\ndiagnostica que la emperatriz\r\npadece lo que él, en griego, llama\r\nkarkinos, y que los romanos, en latín,\r\ndenominan cáncer.\r\nEl enfrentamiento brutal entre sus\r\ndos hijos aboca la dinastía de Julia\r\nal colapso. En medio del dolor físico\r\ny moral que padece la augusta,\r\ncualquiera se hubiera rendido. Se\r\nacumulan tantos desastres que Julia\r\nsiente que es como si luchara contra\r\nlos dioses de Roma.\r\nEn medio del caos, una historia de amor más fuerte que la muerte, una pasión\r\ncapaz de superar pruebas imposibles emerge al rescate de Julia. Nada está\r\nperdido. La partida por el control del imperio continúa', 0, 3, 'images/novels/17.jpg'),
(23, 'Los mares de la canela\r\n(2020)', 'Galicia, China y Filipinas, tres mundos\r\nen el siglo XIX separados por\r\nocéanos y unidos por una mujer\r\ndispuesta a conquistar su libertad.\r\nA finales del siglo XIX, la joven Elba y\r\nsu hermano se ven obligados a huir\r\nde su aldea gallega y realizar una\r\nlarguísima travesía hacia Filipinas. Allí\r\nsu destino quedará inexorablemente\r\ne n l a z a d o c o n e l d e u n r i c o\r\nnegociante chino que ha hecho su\r\nfortuna con el comercio de la\r\ncanela.\r\nGalicia, Filipinas y la isla de Kulangsu, tres mundos unidos por la determinación de\r\nuna mujer dispuesta a conquistar su propia vida. En su largo periplo conocerá la\r\ncerrazón de una sociedad rural, pero también la generosidad de una silenciosa\r\ncadena de mujeres que extiende su solidaridad a través de los océanos entre\r\nEuropa y Asia, en un viaje donde experimentará la incomprensión y la soledad\r\ntanto como el amor y la libertad.\r\nLos mares de la canela, la historia de una mujer capaz de unir tres mundos\r\nseparados por océanos. ', 0, 3, 'images/novels/18.jpg'),
(24, 'El bosque de los cuatro vientos\r\n(2020) \r\n', 'A comienzos del siglo xix, el doctor\r\nVallejo viaja de Valladolid a Galicia junto\r\ncon su hija Marina para servir como\r\nmédico en un poderoso monasterio de\r\nO u r e n s e . A l l í d e s c u b r i r á n u n a s\r\ncostumbres muy particulares y vivirán la\r\ncaída de la Iglesia.\r\nMarina, interesada en la medicina y la\r\nbotánica pero sin permiso para estudiar,\r\nluchará contra las convenciones que su\r\népoca le impone sobre el saber y el\r\namor y se verá inmersa en una aventura\r\nque guardará un secreto de más de mil\r\naños.\r\nEn nuestros días, Jon Bécquer, un inusual\r\nantropólogo que trabaja localizando piezas históricas perdidas, investiga una\r\nleyenda. Nada más comenzar sus indagaciones, en la huerta del antiguo\r\nmonasterio aparece el cadáver de un hombre vestido con un hábito benedictino\r\npropio del xix. Este hecho hará que Bécquer se interne en los bosques de Galicia\r\nbuscando respuestas y descendiendo por los sorprendentes escalones del tiempo.\r\nCon El bosque de los cuatro vientos, María Oruña cambia las tierras cántabras de\r\nsus anteriores obras por su natal y amada Galicia.\r\nUna novela que esconde dos historias en su interior, unidas por el tiempo. ', 0, 3, 'images/novels/19.jpg'),
(25, 'La piel fría\r\n(2002)', 'Un prófugo de la resistencia\r\nirlandesa llega a una pequeña isla\r\naustral para realizar mediciones\r\nmeteorológicas durante un año. Allí\r\nsolo encontrará una cabaña, un\r\nfaro habitado por un personaje\r\nintratable y el inmenso océano que\r\nlo rodea y aísla del resto del mundo.\r\nPero lo peor llega durante la noche,\r\ncuando el refugio se ve asediado\r\npor extrañas criaturas procedentes\r\ndel océano. Sometidos a la\r\na m e n a z a d e l e x t e r i o r, l o s\r\nprotagonistas deberán aprender a\r\nconvivir con lo desconocido para\r\nconseguir sobrevivir.\r\nCon ecos de la narrativa de Conrad, Lovecraft y Stevenson, La piel fría es una\r\nnovela circular de ritmo trepidante y ambiente claustrofóbico sobre los confines\r\nentre los seres humanos y su entorno, la crueldad, el deseo y la incapacidad para\r\ncomunicarse con el otro.\r\nUna inquietante novela de aventuras, terror y ciencia ficción que explora la\r\nesencia del mal y el miedo a lo desconocido que atenaza al ser humano. ', 0, 4, 'images/novels/21.jpg'),
(26, 'El guardián invisible ', '«Ainhoa Elizasu fue la segunda\r\nvíctima del basajaun, aunque\r\nentonces la prensa todavía no lo\r\nllamaba así. Fue un poco más tarde\r\ncuando trascendió que alrededor\r\nde los cadáveres aparecían pelos\r\nde animal, restos de piel y rastros\r\ndudosamente humanos, unidos a\r\nuna especie de fúnebre ceremonia\r\nde purificación. Una fuerza maligna,\r\ntelúrica y ancestral parecía haber\r\nmarcado los cuerpos de aquellas\r\ncasi niñas con la ropa rasgada, el\r\nvello púbico rasurado y las manos\r\ndispuestas en actitud virginal.»\r\nEn los márgenes del río Baztán, en el\r\nvalle de Navarra, aparece el\r\nc u e r p o d e s n u d o d e u n a\r\nadolescente en unas circunstancias\r\nque lo ponen en relación con un\r\na s e s i n a t o o c u r r i d o e n l o s\r\nalrededores un mes atrás.\r\nLa inspectora de la sección de homicidios de la Policía Foral, Amaia Salazar, será\r\nla encargada de dirigir una investigación que la llevará devuelta a Elizondo, una\r\npequeña población de donde es originaria y de la que ha tratado de huir toda su\r\nvida. Enfrentada con las cada vez más complicadas derivaciones del caso y con\r\nsus propios fantasmas familiares, la investigación de Amaia es una carrera\r\ncontrarreloj para dar con un asesino que puede mostrar el rostro más aterrador de\r\nuna realidad brutal al tiempo que convocar a los seres más inquietantes de las\r\nleyendas del Norte. ', 0, 4, 'images/novels/22.jpg'),
(27, 'Legado en los huesos ', 'Un año después de resolver\r\nl o s c r í m e n e s q u e\r\naterrorizaron al pueblo del\r\nBaztán, la inspectora Amaia\r\nSalazar acude embarazada\r\nal juicio contra Jasón\r\nMedina, el padrastro de\r\nJohana Márquez, acusado\r\nde violar, mutilar y asesinar a\r\nla joven imitandolos\r\nasesinatos del caso\r\nbasajaun.\r\nPero, tras el suicidio del\r\na c u s a d o , e l j u i c i o\r\ndebe cancelarse y Amaia\r\nes reclamada por la policía\r\nporque se ha hallado una\r\nnota que contiene un\r\ne s c u e t o e\r\ninquietante m e n s a j e :\r\n«Tarttalo». Esa sola palabra\r\nd e s t a p a r á u n a t r a m a\r\nterrorífica tras la búsqueda\r\nde la verdad.\r\nLegado en los huesos se corresponde con la segunda parte de la Trilogía del\r\nBaztán, considerada como un trabajo ejemplar de la escritora vasca, Dolores\r\nRedondo, dentro del género de la novela negra. ', 0, 4, 'images/novels/23.jpg'),
(28, 'Ofrenda a la tormenta ', 'Ha pasado ya un mes desde que la\r\ninspectora de la Policía Foral recuperó a\r\nsu hijo y pudo detener a Berasategui.\r\nP e r o a p e s a r d e q u e t a n t o l a\r\nGuardia Civil como el juez Markina dan\r\npor muerta a Rosario, Amaia siente que\r\nno está libre de peligro, un desasosiego\r\nque sólo Jonan comprende.\r\nLa muerte súbita de una niña en Elizondo\r\nresulta sospechosa: el bebé tiene unas\r\nmarcas rojizas en el rostro que indican\r\nque ha habido presión digital, y además,\r\nsu padre intenta llevarse el cadáver.\r\nLa bisabuela de la pequeña sostiene que\r\nla tragedia es obra de Inguma, el\r\ndemonio que inmoviliza a los durmientes,\r\nse bebe su aliento y les arrebata la\r\nvida durante el sueño. Pero serán los\r\nanálisis forenses del doctor San Martín los\r\nque convencen a Amaia\r\nSalazar de investigar otras muertes de bebés, que pronto revelarán un rastro\r\ninaudito en el valle.\r\nBerasategui muere, entonces, inexplicablemente en su celda, lo que despliega\r\nuna trepidante investigación que llevará a Amaia al auténtico origen de los\r\nsucesos que han asolado el valle de Baztán. Y mientras, desde el bosque, una\r\nimpresionante tormenta llega para sepultar la verdad más demoledora.\r\nOfrenda a la tormenta se corresponde con la tercera y última parte de la Trilogía\r\ndel Baztán, considerada como un trabajo ejemplar de la escritora vasca, Dolores\r\nRedondo, dentro del género de la novela negra. ', 0, 4, 'images/novels/24.jpg'),
(29, 'Fariña\r\n(2015)\r\nNacho Carretero ', 'Coca, farlopa, perico, merca, Fariña.\r\nNunca Galicia comercializó un producto\r\ncon tanto éxito. Aunque ahora parezca\r\nuna pesadilla lejana, en los años 90 el 80\r\npor ciento de la cocaína desembarcaba\r\nen Europa por las costas gallegas.\r\nA través de testimonios directos de\r\nc a p o s , p i l o t o s d e p l a n e a d o r a s ,\r\narrepentidos, jueces, policías, periodistas\r\ny madres de toxicómanos, Nacho\r\nCarretero retrata con minuciosidad este\r\npaisaje criminal.\r\nFariña incluye, además, un repaso inédito por los clanes que siguen operando hoy\r\nen día.\r\nEl libro Fariña nos relata una historia contemporánea sobre el lucro desmedido\r\nque obtuvieron los traficantes de sustancias ilícitas, comercializando un producto\r\ndañino y totalmente fuera de la legalidad, ya que proporciona enormes ingresos\r\na expensas de la vida humana. ', 0, 4, 'images/novels/25.jpg'),
(30, 'La mala hierba (2017)', '“Nada crece sano en esta tierra\r\nenferma.\r\nPero la verdad siempre resurge, como\r\nla mala hierba.”\r\nTras perder su empleo, Jacobo se ve\r\nobligado empezar una nueva vida\r\njunto a Irene, su esposa, y Miriam, la hija\r\nadolescente de ambos, en las afueras\r\nde Portocarrero, un pueblo en pleno\r\ndesierto de Almería donde no crece\r\nnada salvo la mala hierba. Jamás\r\npensó que el tiempo que pasan allí\r\np o d í a t e r m i n a r d e f o r m a t a n\r\ndramática: unos desconocidos irrumpen en su viejo cortijo. Irene es asesinada.\r\nJacobo, herido, cae en coma.\r\nSin embargo, el infierno no ha hecho más que empezar. Meses después, cuando\r\nJacobo despierta, la Guardia Civil le pone al tanto de los avances en la\r\ninvestigación. Tienen a un culpable. Al responsable que ordenó su asesinato. Y no\r\nes otro que su propia hija de catorce años: Miriam.\r\nCon la ayuda de Nora, la singular abogada de Miriam, que cree firmemente en la\r\ninocencia de su cliente, Jacobo intentará descubrir qué sucedió realmente esa\r\nnoche. Pero a medida que avanza la investigación, saldrán a la luz nuevos\r\ninterrogantes que afectan a la cerrada comunidad de Portocarrero, donde nadie\r\nparece inocente.\r\nLa mala hierba es una novela repleta de suspense e intensidad que no dan\r\ntregua al lector, y lo atrapan en un envolvente thriller lleno de ritmo, dramatismo,\r\ngiros inesperados y un desenlace sorprendente. ', 0, 4, 'images/novels/26.jpg'),
(31, 'Saga Neimhaim- Neimhaim.\r\nLos hijos de la nieve y la tormenta\r\n(2015-2018) ', 'Dos pueblos. Dos grandes clanes. Una\r\ntierra apartada del resto del mundo.\r\nAmante del coraje y de las armas era el\r\nclan Kranyal; guerreros de bravo\r\ncorazón y maestría en el arte de la\r\nlucha. Protectores de la vida y la\r\nserenidad eran los Djendel, pacíficos\r\nsacerdotes bendecidos con habilidades\r\nque iban más allá de lo natural, cuyo\r\nuso restringían con estrictos códigos.\r\nSus historias discurrían por separado,\r\npero un día la frágil armonía quedó\r\nalterada y el entramado del destino\r\ncambió para siempre. Ambos pueblos\r\nsalvaron sus recelos y unieron sus\r\ncaminos por la fuerza de la necesidad.\r\nJuntos fundaron un joven reino llamado\r\nNeimhaim.\r\nAsí comienza la historia de los Hijos de la Nieve y la Tormenta.\r\nNeimhaim. Los hijos de la nieve y la tormenta es considerada una novela de\r\nfantasía épica única y sublime que crea un mundo y unos personajes a la altura\r\nde las mejores obras de fantasía conocidas hasta la fecha.', 0, 5, 'images/novels/28.jpg'),
(32, 'Neimhaim.\r\nEl azor y los cuervos \r\n', 'A qué puedes aspirar si tus padres\r\nson un mito? ¿Puede un héroe\r\nrenunciar a tomar su espada?\r\nJörn es el hijo de los Reyes Blancos y\r\nllega al mundo bajo la sombra de\r\nuna leyenda viva. Como tal, se\r\nespera que cumpla un gran destino.\r\nSin embargo Jörn no desea la vida\r\nque todos han dispuesto para él. Él\r\nsolo aspira a vivir en las montañas en\r\nsoledad.\r\nPero una sombra se cierna sobre él y\r\nsobre todo el reino de Neimhaim, y\r\nJörn se verá en una encrucijada,\r\nforzado a tomar una decisión si\r\nquiere defender a los suyos. Un\r\nnuevo compañero de ar mas,\r\nCyannan, le acompañará.\r\nEntre tanto, un secreto está a punto\r\nde desvelarse. Una verdad guardada celosamente que concierne a dos\r\nhermanos gemelos, quienes van a descubrir de la peor forma posible que no son\r\nquienes creían ser…\r\nNeimhaim. El azor y los cuervos es mucho más que una novela de fantasía;\r\nrompe con los tópicos que envuelven a la figura del héroe y se atreve a redefinirlo\r\nsegún los cánones más modernos. ', 0, 5, 'images/novels/29.jpg'),
(33, 'Rojo y Oro\r\n(2017) ', 'Orión está cansado de ser el\r\nesclavo de Hera desde que su\r\nmadre, la diosa del Caos, fue\r\ncondenada por su ambición.\r\nHera le ha tratado siempre más\r\ncomo un criado que como el\r\ndios que es. Y quiere que eso\r\nacabe.\r\nAsteria está cansada de luchar.\r\nDesde que el pueblo de las\r\namazonas fue arrasado hace\r\naños, ella y sus hermanas viven\r\nesclavizadas y obligadas a servir\r\nal Emperador de Élada como\r\ngladiadoras. Y quiere que eso acabe.\r\nEl mundo de Orión es dorado como solo puede serlo la grandeza de los dioses; el\r\nmundo de Asteria es rojo como solo puede serlo la sangre que derrama cada día.\r\nAmbos buscan venganza hacia quienes los encadenaron en esos mundos.\r\nAmbos buscan libertad, y harán lo que sea necesario para conseguirla.\r\nRojo y Oro es una fantasía histórica fascinante de las autoras más prometedoras\r\ndel género fantástico en España. ', 0, 5, 'images/novels/30.jpg'),
(34, 'El arcano y el jilguero\r\n(2019) \r\n', 'Mezen el Ariete es un Arcano\r\ndel Tormento, un demonio\r\ni n m o r t a l q u e d i s f r u t a\r\ndesollando a sus víctimas. Su\r\noficio, torturador al servicio\r\ndel Imperio, lo ha llevado a\r\ncometer crímenes aberrantes\r\ncontra personas indefensas, y\r\nla única ayuda con la que\r\ncuenta para sobrellevar la\r\nculpa es el convencimiento\r\nprofundo de que lo hace por\r\nun bien mayor. Pasa los días\r\nviajando de un frente a otro,\r\nrindiendo ciudades asediadas\r\ny sofocando rebeliones para\r\ne l E m p e r a d o r T h i e n\r\nS e e d v e e n , u n t i r a n o\r\nmegalómano del que ha\r\njurado vengarse en cuanto\r\nno haya más tierras por conquistar.\r\nSin embargo, el precario equilibrio de la danza que debe bailar para perseguir sus\r\npropios fines mientras finge lealtad al Imperio se ve alterado cuando conoce a\r\nNara, una huérfana de guerra que no lo trata como al monstruo que él mismo\r\ncree ser.\r\nEl arcano y el jilguero construye na historia con elementos narrativos sólidos que\r\npueden invitar a descubrir el género a lectores ávidos de nuevas experiencias en\r\nel género fantástico.', 0, 5, 'images/novels/31.jpg'),
(35, 'Barro\r\n(2020) ', 'Alicia vive a la sombra de su\r\nhermana, Lucía, una sombra\r\noscura que se proyecta\r\ndesde el centro donde sus\r\npadres la encerraron. Desde\r\nentonces no se puede\r\nhablar de ella, es como si\r\nnunca hubiera existido.\r\nAlicia, agotada, decide\r\nmarcharse de casa, sueña\r\ncon instalarse en París,\r\ndonde escribirá y compartirá\r\nsu vida solo con personas a\r\nlas que quiera de verdad.\r\nPero Lucía muere y Alicia\r\ndebe ir al centro a recoger\r\nsus cosas.\r\nAllí, sin que nadie sepa por qué, una puerta que conecta dos mundos se traga a\r\nAlicia, que perderá su nombre y su memoria. Tendrá que recuperar ambos para\r\nvolver y cumplir sus sueños, pero ¿cómo se recobran los recuerdos si no sabes que\r\nlos has perdido?\r\nBarro bebe de Alicia en el país de las maravillas y La historia interminable, y\r\npresenta una fantasía de portal bella y oscura plagada de juegos de imágenes y\r\nmetáforas. Disfrutarás esta novela si te gustan los relatos con un alto componente\r\nde ensoñación en los que el lector tiene tanto que decir como la autora.', 0, 5, 'images/novels/32.jpg');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `autores`
--
ALTER TABLE `autores`
  ADD PRIMARY KEY (`id_autor`);

--
-- Indices de la tabla `generos`
--
ALTER TABLE `generos`
  ADD PRIMARY KEY (`id_genero`);

--
-- Indices de la tabla `novelas`
--
ALTER TABLE `novelas`
  ADD PRIMARY KEY (`id_novela`),
  ADD KEY `id_genero` (`id_genero`) USING BTREE,
  ADD KEY `id_autor2` (`id_autor`) USING BTREE;

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `autores`
--
ALTER TABLE `autores`
  MODIFY `id_autor` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;

--
-- AUTO_INCREMENT de la tabla `generos`
--
ALTER TABLE `generos`
  MODIFY `id_genero` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT de la tabla `novelas`
--
ALTER TABLE `novelas`
  MODIFY `id_novela` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=36;

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `novelas`
--
ALTER TABLE `novelas`
  ADD CONSTRAINT `novelas_ibfk_3` FOREIGN KEY (`id_genero`) REFERENCES `generos` (`id_genero`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `novelas_ibfk_4` FOREIGN KEY (`id_autor`) REFERENCES `autores` (`id_autor`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
